### ISSUE TITLE
Hard to Update Entries

### ISSUE THREAD

**Issue by kolatubosun** [Yorubaname/yorubaname-website#25] opened 2016-07-03 10:58 UTC
This issue has been with us since launch. How it manifests itself is that after you've completed all the required entries for a name on the dashboard, and then you click "save" or "publish" at the bottom of the page, you get the red alert of death in the top right corner saying "entry can't be updated" (screenshot attached). Then you will be forced to refresh, losing all your entries, and then do it all over again. Most times, it finally works on the second trial. 

So what I've always done (which is probably why I'm currently the only one able to update entries) is that as soon as I enter the edit mode for a name, I fill in just letters that make no sense (e.g. "err") in all the compulsory spaces, and then click "save". If it shows me the red error, I refresh, then do it again until it shows green. Then I start changing the letters to the real content, one by one, clicking "save" after each filling to be sure that it's saving and I don't lose all the information at once. Eventually I finish, and then publish.

This problem also comes up when one is editing the "name" field itself. For all the entries, even if they were entered with capital letters at the beginning of the word (e.g. Adebola), when it moves from "suggested names" to "unpublished names", it changes it into all small letters (e.g. adebola). I think I filed a bug for this at the time. So, when you try to change the first "a" to "A", and you try to save, it shows that red error the first time. Then you refresh and try it again then it finally updates. 

The same happens with tone markings as well. Most names entered don't have complete or accurate tone markings. But when, in the edit mode, you change the tone marking on the name field, it first doesn't update, until you refresh and try again.

All these have discouraged new lexicographers who haven't figured out the trick and just assumed that it is impossible to update old entries or flesh out new ones.

What is the cause of this bug and can it be fixed asap, especially now that our road trip has won us a few new lexicography contacts?
![screenshot 22](https://cloud.githubusercontent.com/assets/18510601/16545046/44d9ca9c-4115-11e6-98a7-869901b57389.png)

**Comment by kolatubosun** [comment] 2016-08-04 06:09
Comment received last night from a volunteer: "Nothing I tried to do tonight worked. I tried to edit some names first, but the entries wouldn't save. Then I tried adding a few, the entries didn't submit."

If we can make this the first bug to be fixed, please let's do that. cc @temiyemi

**Comment by dadepo** [comment] 2016-08-07 19:11
When an account with "basic lexicography" role is created, the `roles` value is malformed "there is an extra ROLE_ string in the value". This should be looked into as part of the causes (if not the main cause) of this problem.

**Comment by dadepo** [comment] 2016-08-21 21:01
Code changes that removes the extra "ROLE_" has been made. I will close this ticket once it is in production

**Comment by kolatubosun** [comment] 2016-08-21 21:04
Any luck with the errors in admin account preventing updates until a refresh is done?

**Comment by dadepo** [comment] 2016-08-21 21:23
No. not yet. I have not gotten the chance to take a look at the last screenshot you sent me.

**Comment by dadepo** [comment] 2016-09-13 10:30
Deployed

**Closed by dadepo** 2016-09-13 10:30 UTC
Labels: bug, High
